# Generated by Django 5.0.2 on 2024-02-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='dummy.png', upload_to='profile_pics/'),
        ),
    ]
