# Generated by Django 5.0.2 on 2024-02-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_content_post_caption_post_no_of_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
