# Generated by Django 5.0.2 on 2024-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_chatmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
