# Generated by Django 5.0.2 on 2024-03-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='already_liked',
            field=models.BooleanField(default=False),
        ),
    ]
