# Generated by Django 5.0.2 on 2024-03-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_like_already_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='already_liked',
        ),
    ]
