# Generated by Django 5.0.2 on 2024-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_like_already_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
