# Generated by Django 5.0.2 on 2024-03-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_userprofile_dark_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_active',
            new_name='is_online',
        ),
    ]
